sudo: required
services:
  - docker

before_install: 
  - docker build -t jeffkk512/docker-react -f Dockerfile.Dockerfile.dev .

script: 
  - docker run -e CI=true jeffkk512/docker-react npm run test -- ----coverage

